qrflow/qrflow/core/urls.py
from django.conf import settings
from django.urls import path, re_path, include
from django.conf.urls.static import static, serve

from core import views


app_name = 'core'

urlpatterns = [
    path(r"organization/", views.OrganizationListView.as_view(), name="organization-list"),
    path(r"organization/<uuid:pk>/", views.OrganizationDetailView.as_view(), name="organization-detail"),
]

qrflow/qrflow/flow/urls.py
from django.urls import path, include

from flow import views


app_name = 'flow'

urlpatterns = [

    path(r"application/<uuid:pk>/", views.ApplicationDetailView.as_view(), name="application-detail"),
    path(r"application/<uuid:pk>/scanner/", views.ApplicationScannerView.as_view(), name="application-scanner"),

    path(r"code/<uuid:pk>/", views.CodeDetailView.as_view(), name="code-detail"),

]

qrflow/qrflow/pki/urls.py
from django.conf import settings
from django.urls import path, re_path, include
from django.conf.urls.static import static, serve


app_name = 'pki'

urlpatterns = []

qrflow/qrflow/qrflow/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static, serve

from rest_framework import permissions
from rest_framework.authtoken import views as auth_views

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView, TokenBlacklistView

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from qrflow import views, __version__
from core.api import router as core_api
from flow.api import router as flow_api


schema_view = get_schema_view(
   openapi.Info(
      title="QR-Flow API",
      default_version=__version__,
      description="QR-Flow Management API",
      terms_of_service="https://www.landercy.be/terms/",
      contact=openapi.Contact(email="info@qrflow.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.IsAuthenticatedOrReadOnly],
)


urlpatterns = [

    # Static & Media:
    #re_path("r^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}, name="static-server"),
    path(r"media/<path:path>", views.FileServerView.as_view(), name="file-server"),

    # Admin & Accounts:
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls', 'django.contrib.auth'), namespace='account')),
    path("accounts/profile/", views.ProfileView.as_view(), name="profile"),

    # API (DRF):
    #path('api-auth/', include('rest_framework.urls')),
    #path('api-token-auth/', auth_views.obtain_auth_token),
    path('api/token/issue/', TokenObtainPairView.as_view(), name='token-obtain-pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token-verify'),
    path('api/token/blacklist/', TokenBlacklistView.as_view(), name='token-blacklist'),
    path('api/core/', include((core_api.urls, 'core-api'), namespace="core-api")),
    path('api/flow/', include((flow_api.urls, 'flow-api-model'), namespace="flow-api-model")),
    path('api/flow/', include('flow.api', "flow-api")),

    # DRF+Swagger:
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # Applications:
    path('core/', include('core.urls', namespace="core")),
    path('pki/', include('pki.urls', namespace="pki")),
    path('flow/', include('flow.urls', namespace="flow")),

    # Home:
    path('', views.ProjectHomeView.as_view(), name='index'),

]

# Add prefix to classical URL:
urlpatterns = [path(f'{settings.URL_PREFIX}', include(urlpatterns))]

# Compose prefix in settings for specific URL:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qrflow/qrflow/flow/models.py
import base64
import json
from urllib.parse import urlparse

import barcode
from django.db import models
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile

from encrypted_json_fields import fields as efields

from qrflow import constants
from core.models import AbstractBaseModel, AbstractOwnershipModel
from flow import managers
from flow.helpers import QRCodeHelper, DataMatrixHelper, EC2KeyDGCHelper, EPCHelper, BarcodeHelper


class Endpoint(AbstractBaseModel, AbstractOwnershipModel):

    class Meta:
        unique_together = ("organization", "name")
        ordering = ("name",)

    name = models.CharField(max_length=128, unique=False)
    method = models.CharField(max_length=8, choices=constants.HTTP_METHODS, default='GET', help_text="HTTP method to contact the endpoint")
    target = models.URLField(help_text="Endpoint target URL (raw or template)")
    parameters = models.JSONField(blank=True, default=dict, help_text="Specific parameters to contact the endpoint (excluded credentials)")
    credentials = efields.EncryptedJSONField(default=dict, null=True, blank=True)

    # def __str__(self):
    #     return "%s: %s %s" % (self.name, self.method, self.target)


class Application(AbstractBaseModel, AbstractOwnershipModel):

    class Meta:
        unique_together = ("organization", "name")
        ordering = ("name",)

    objects = managers.ApplicationManager()
    name = models.CharField(max_length=128, unique=False, help_text="Application name")
    credentials = efields.EncryptedJSONField(default=dict, null=True, blank=True)
    #scanner_mode = models.CharField(max_length=16, choices=constants.SCANNER_MODES, default='RPC', help_text="Scanner mode")
    forward_endpoint = models.ForeignKey(Endpoint, on_delete=models.RESTRICT, null=True, blank=True)
    repeat_scan = models.BooleanField(default=False, null=False)
    ajax_mode = models.BooleanField(default=False, null=False)
    auto_post = models.BooleanField(default=False, null=False)
    scan_delay = models.FloatField(default=2.5, null=False)


class Code(AbstractBaseModel):

    class Meta:
        unique_together = ("application", "name")
        ordering = ("zorder", "name")

    def image_path(self, filename):
        return "organizations/{}/applications/{}/codes/{}".format(
            self.application.organization.id.hex,
            self.application.id.hex,
            self.id.hex + ".png"
        )

    application = models.ForeignKey(Application, on_delete=models.RESTRICT, related_name="codes")
    code_type = models.CharField(max_length=16, choices=constants.CODE_TYPES, default='QR', help_text="Type of code")
    name = models.CharField(max_length=256, unique=False)
    payload = models.JSONField(default=dict, null=True, blank=True)
    image = models.ImageField(upload_to=image_path, max_length=512, null=False, blank=True)
    zorder = models.IntegerField(default=0)

    @property
    def base64(self):
        return "data:image/png;base64, %s" % base64.b64encode(self.image.read()).decode()

    def save(self, *args, **kwargs):

        if self.code_type == "QR":
            image = QRCodeHelper.render(self.payload["message"])
        elif self.code_type == "QR-JSON":
            image = QRCodeHelper.render(json.dumps(self.payload))
        elif self.code_type == "QR-EPC":
            image = QRCodeHelper.render(EPCHelper.encode(**self.payload))
        elif self.code_type == "QR-DGC":
            image = QRCodeHelper.render(EC2KeyDGCHelper.encode(self.payload))
        elif self.code_type == "DM":
            image = DataMatrixHelper.render(self.payload["message"])
        elif self.code_type in barcode.PROVIDED_BARCODES:
            image = BarcodeHelper.render(self.payload["message"], class_name=self.code_type)
        else:
            image = QRCodeHelper.render("Not implemented :(")

        if self.image:
            self.image.storage.delete(self.image.path)

        self.image = InMemoryUploadedFile(image, 'ImageField', 'code.png', 'PNG', image.getbuffer().nbytes, None)

        super().save(*args, **kwargs)


class Log(AbstractBaseModel):

    class Meta:
        ordering = ("-created",)

    application = models.ForeignKey(Application, on_delete=models.CASCADE, null=True, blank=True)
    endpoint = models.ForeignKey(Endpoint, on_delete=models.CASCADE, null=True, blank=True)
    status = models.IntegerField(null=True, blank=False)
    payload = models.JSONField(null=True, blank=False)
    response = models.JSONField(null=True, blank=False)

qrflow/qrflow/flow/forms.py
from django import forms


class ApplicationScannerForm(forms.Form):
    organization = forms.CharField(widget=forms.HiddenInput())
    application = forms.CharField(widget=forms.HiddenInput())
    repeat_scan = forms.BooleanField(required=False, disabled=False)
    scan_delay = forms.FloatField(required=False, disabled=False)
    auto_post = forms.BooleanField(required=False, disabled=False)
    payload = forms.JSONField(required=False, disabled=False, initial=dict)

qrflow/qrflow/flow/views.py
from django.shortcuts import render, reverse
from django.views.generic import TemplateView, ListView, DetailView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

import requests

from core.permissions import OrganizationPermissionMixin, RelatedOrganizationPermissionMixin
from flow import models, forms


class ApplicationDetailView(OrganizationPermissionMixin, DetailView):
    model = models.Application

    # def get(self, request, *args, **kwargs):
    #     response = super().get(self, request, *args, **kwargs)
    #     response.set_cookie("application", kwargs["pk"])
    #     return response


class ApplicationScannerView(DetailView, FormView):
    template_name = "flow/application_scanner.html"
    model = models.Application
    form_class = forms.ApplicationScannerForm

    def get_success_url(self):
        return reverse('flow:application-scanner', kwargs={'pk': self.kwargs["pk"]})

    def get_initial(self):
        initial = super().get_initial()
        application = models.Application.objects.get(pk=self.kwargs['pk'])
        initial['organization'] = application.organization.id
        initial['application'] = application.id
        initial['repeat_scan'] = application.repeat_scan
        initial['scan_delay'] = application.scan_delay
        initial['auto_post'] = application.auto_post
        return initial

    def form_valid(self, form):

        application = models.Application.objects.get(pk=self.kwargs['pk'])

        if application.forward_endpoint:
            try:

                # API Endpoint Call:
                response = requests.request(
                    application.forward_endpoint.method,
                    url=application.forward_endpoint.target,
                    headers={},
                    json=form.cleaned_data,
                    timeout=1.
                )

                # Log API request/response cycle:
                models.Log.objects.create(
                    application=application,
                    endpoint=application.forward_endpoint,
                    status=response.status_code,
                    payload=form.cleaned_data,
                    response=response.json()
                )
                messages.info(self.request, response.json())

            except Exception as error:
                messages.error(self.request, "Payload not submitted, try again.")

        return super().form_valid(form)


class CodeDetailView(RelatedOrganizationPermissionMixin, DetailView):
    related_organization_field = "application"
    model = models.Code

qrflow/qrflow/flow/templates/flow/application_detail.html
{% extends "base.html" %}

{% block content %}
    {% load static %}

    <div class="row col-sm-12 p-2">
        <h3 class="page-header">
            <i class="bi bi-person-circle"></i> <a href="{% url 'profile' %}">{{ user.username }}</a>
            <i class="bi bi-chevron-compact-right"></i>
            <i class="bi bi-diagram-3"></i> <a href="{% url 'core:organization-detail' object.organization.id %}">{{ object.organization.name }}</a>
            <i class="bi bi-chevron-compact-right"></i>
            <i class="bi bi-app-indicator"></i> {{ object.name }}
        </h3>
        <p>Select your code or scan.</p>
    </div>

    <div class="row col-sm-12 p-2">
        <p><a href="{% url 'flow:application-scanner' object.id %}" class="btn btn-primary"><i class="bi bi-upc-scan"></i> Scanner</a></p>
    </div>

    <div class="row col-sm-12 p-2">
        <h4 class="page-header"><i class="bi bi-upc"></i> Codes</h4>
    </div>

    <div class="row col-sm-12 p-2">

        {% for item in object.codes.all %}
        <div class="col-sm-3">
            <a href="{% url 'flow:code-detail' item.id %}" class="col-sm-2 text-center">
            <div class="card m-3">
                <div class="card-body">
                    <h5 class="card-title">{{ item.name }}</h5>
                    <img src="{{ item.image.url }}" width="90%;" />
                    <p class="card-text">{{ item.description }}</p>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}

    </div>

{% endblock %}

qrflow/qrflow/flow/templates/flow/application_scanner.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block headers %}
    <!-- HTML5-QRCode (https://github.com/mebjas/html5-qrcode) -->
    <script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>

    <!-- highligh.js -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/atom-one-dark.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>
{% endblock %}

{% block content %}
    {% load static %}
    <div class="row col-sm-12 p-2">
        <h3 class="page-header">
            <i class="bi bi-person-circle"></i> <a href="{% url 'profile' %}">{{ user.username }}</a>
            <i class="bi bi-chevron-compact-right"></i>
            <i class="bi bi-diagram-3"></i> <a href="{% url 'core:organization-detail' object.organization.id %}">{{ object.organization.name }}</a>
            <i class="bi bi-chevron-compact-right"></i>
            <i class="bi bi-app-indicator"></i> <a href="{% url 'flow:application-detail' object.id %}">{{ object.name }}</a>
            <i class="bi bi-chevron-compact-right"></i>
            <i class="bi bi-upc-scan"></i> Scanner
        </h3>
    </div>

    <!-- QR Code Reader -->
    <div class="row col-sm-12 p-2">
        <p class="btn btn-success col-sm-4" style="visibility: hidden;" id="id_scanned_label">Scanned</p>
    </div>
    <div class="row col-sm-12 p-2">
        <div id="qr-reader" class="col-sm-4"></div>
        <div class="col-sm-8">
            {% if object.ajax_mode %}
            <form>
            {% else %}
            <form method="post">
            {% endif %}
                <div style="display: none;">
                {% csrf_token %}
                {{ form|crispy }}
                {% if object.ajax_mode %}
                {% else %}
                <input type="submit" value="Submit" id="id_submit" class="btn btn-primary" />
                {% endif %}
                </div>
            </form>
        </div>
    </div>


    <script type="text/javascript">
        var application_ajax_mode = {{ object.ajax_mode|lower }};
        var application_target_url = "{{ object.forward_endpoint.target }}";
        var application_request_mode = "{{ object.forward_endpoint.method }}";
    </script>
    <script src="{% static 'js/scanner.js' %}" type="text/javascript"></script>

{% endblock %}

qrflow/qrflow/flow/templates/flow/code_detail.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <div class="row col-sm-12 p-2">
        <h3 class="page-header">
            <i class="bi bi-person-circle"></i> <a href="{% url 'profile' %}">{{ user.username }}</a>
            <i class="bi bi-chevron-compact-right"></i>
            <i class="bi bi-diagram-3"></i> <a href="{% url 'core:organization-detail' object.application.organization.id %}">{{ object.application.organization.name }}</a>
            <i class="bi bi-chevron-compact-right"></i>
            <i class="bi bi-app-indicator"></i> <a href="{% url 'flow:application-detail' object.application.id %}">{{ object.application.name }}</a>
            <i class="bi bi-chevron-compact-right"></i>
            <i class="bi bi-upc"></i> {{ object.name }}
        </h3>
    </div>

    <div class="row col-sm-12 p-2">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Key</th>
                    <th scope="col">Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">Organization</th>
                    <td>
                        {{ object.application.organization.name }}
                        (<code>{{ object.application.organization.id }}</code>)
                    </td>
                </tr>
                <tr>
                    <th scope="row">Application</th>
                    <td>
                        {{ object.application.name }}
                        (<code>{{ object.application.id }}</code>)
                    </td>
                </tr>
                <tr>
                    <th scope="row">Code</th>
                    <td>
                        {{ object.name }}
                        (<code>{{ object.id }}</code>)
                    </td>
                </tr>
                <tr>
                    <th scope="row">Image</th>
                    <td><img src="{{ object.image.url }}" /></td>
                </tr>
                <tr>
                    <th scope="row">Payload</th>
                    <td><pre>{{ object.payload }}</pre></td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}